image:
  file: .gitpod.dockerfile
tasks:
    - init: |
          pip install -r requirements.txt
          npm i -g@angular/cli
          cd Project
          python app_riders.py
          cd Riders_Hub
          npm install
          
    